/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description サイドカーが応答することの確認
     */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Pages
     * @description アーカイブ内のページを viewer と同じ並びで返す
     */
    get: operations["list_pages_api_pages_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/thumb": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Thumbnail
     * @description ページのサムネイルを返す
     */
    get: operations["thumbnail_api_thumb_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/edits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Edits
     * @description 本ごとに、サムネイル・並べ替え・分割結合のどれを施したかを返す。
     *
     *     整理の画面が、近道のアイコンに編集済みの印を出すのに使う（#143）。
     *     読むのは本の中の記録だけなので、一覧の冊数ぶんまとめて 1 回で返す。
     */
    post: operations["edits_api_edits_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve
     * @description ドロップされたファイルを実パスに結びつける。
     *
     *     ブラウザは実パスを渡さないが、名前とサイズは分かる。許可された場所の
     *     中から同じものを探せば、ドロップからでも対象を特定できる。同名が複数
     *     あってサイズでも絞れない場合は、勝手に選ばず返す。
     */
    post: operations["resolve_api_resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/browse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Browse
     * @description 許可された場所の中を辿る。
     *
     *     ブラウザはドロップされたファイルの実パスを取得できないため、
     *     サーバー側で辿って選んでもらう。Tauri ではネイティブのドロップも
     *     使えるが、同じ画面で両方使えるようにする。
     */
    get: operations["browse_api_browse_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Entries
     * @description タイトルと著者の辞書。query を与えると絞り込む。
     *
     *     絞り込まないときは全件を返す。画面はこの一覧の完全一致で著者を即座に
     *     埋め、外れたときだけ外部検索へ回る（元の Tkinter 版も辞書全体を引いて
     *     いた）。件数で切ると、辞書に入っている作品名でも毎回ネットワークへ出て
     *     数秒待たされる（#125）。
     */
    get: operations["list_entries_api_library_entries_get"];
    put?: never;
    /**
     * Save Entry
     * @description 辞書に記録する。同じタイトルがあれば上書きする
     */
    post: operations["save_entry_api_library_entries_post"];
    /**
     * Delete Entry
     * @description 辞書から取り除く
     */
    delete: operations["delete_entry_api_library_entries_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Entries
     * @description 整理済みの蔵書から拾った対を、まとめて辞書へ取り込む（#73 段階 6）。
     *
     *     1 件ずつの記録と違い、辞書に無い作品名だけを足す。既にある著者は
     *     著者が違っても上書きしない。この表は以降のすべての整理で著者欄を
     *     埋めるので、利用者が手で直した著者を潰すと直した覚えが黙って消える。
     *     断ったものは食い違いとして返し、画面から見えるようにする。
     */
    post: operations["import_entries_api_library_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/suggest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Suggest
     * @description 外部サービスから著者名を補完する。
     *
     *     ネットワークに出るため失敗しうる。見つからない場合と区別せず、
     *     空の結果として返して画面を止めない。
     */
    post: operations["suggest_api_library_suggest_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/image": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Image
     * @description ページを原寸で返す。拡大表示に使う
     */
    get: operations["image_api_image_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/original": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Original
     * @description いま見ている 1 枚の、加工前の画像そのものを返す。
     *
     *     求めるのは加工後のページ名だけで、元画像が ZIP のどのエントリに
     *     入っているかは受け取らない。エントリ名を外から取ると、書き換えられた
     *     manifest 経由でアーカイブ内の任意のエントリを読ませる道ができる。
     *
     *     バイト列を /api/cover と分けているのは、画像が JSON に載らないうえ、
     *     /api/cover は画面を描き直すたびに引かれる軽い経路であってほしいため。
     */
    get: operations["original_api_original_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cover
     * @description サムネイルにする候補 1 枚の状態を返す。name を省くと先頭ページ。
     *
     *     viewer は縦長 2:3 に中央クロップして描くため、横長だと表紙が
     *     見えない。UI で加工を促せるよう、見開きかどうかを添える。
     *
     *     寸法と見開き判定をここで返すのは、UI が切り抜き枠を元画像の画素へ
     *     写すのに必要だから。画面側で画像から測り直すと、判定の基準が
     *     サーバーと二重になり、片方だけずれても気づけない。
     *
     *     元画像の有無も同じ応答に載せる。画面は「どれだけ広い絵を出すか」と
     *     「枠をどこに置くか」を 1 度に決める。別の入口に分けると、2 回
     *     問い合わせる間に片方だけ古い値を見た状態が作れてしまう。
     */
    get: operations["cover_api_cover_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/cover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Cover
     * @description 表紙の加工をジョブとして投入する
     */
    post: operations["submit_cover_api_jobs_cover_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description 新しい順にジョブを並べる
     */
    get: operations["list_jobs_api_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Job
     * @description ジョブ 1 件の状態を、経過のログとともに返す
     */
    get: operations["get_job_api_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Job
     * @description 実行中のジョブにキャンセルを要求する
     */
    post: operations["cancel_job_api_jobs__job_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Reorder
     * @description ページ並べ替えをジョブとして投入する
     */
    post: operations["submit_reorder_api_jobs_reorder_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/split-scan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Split Scan
     * @description 見開きを割る画面に並べる行を、ジョブとして走査する（#58 段階 2）。
     *
     *     数百枚の ZIP を 1 枚ずつ開くので要求の中では終わらない。パスの検証と
     *     「そもそも開けるか」は投入のこの時点で済ませる。ジョブを作ってから
     *     失敗させると、許可の外を指したことが「失敗したジョブ」としてしか
     *     残らず、画面は投入できたと思ってしまう。
     */
    post: operations["submit_split_scan_api_jobs_split_scan_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/split": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Split
     * @description 割った結果を書き込むジョブを投入する（#58 段階 2）。
     *
     *     断るものは、すべてジョブを作る前に断る。ZIP を丸ごと書き直す処理
     *     なので、受け付けてから失敗させると、画面は割れたつもりで先へ進む。
     *     見るのは順に、許可された場所か・走査したときから本が動いていないか
     *     （印）・行の名前を並べたものがいまのページ順と一致するか。どこで
     *     断ってもアーカイブは 1 バイトも変わらない。
     */
    post: operations["submit_split_api_jobs_split_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Analysis
     * @description 展開せずに目次を読み、出来上がる本を実行前に並べる（#70）。
     *
     *     利用者はチェックを外す前に「何が出来るのか」を見る必要がある。
     *     整理と同じ展開・同じ巻数判定を通すので、ここで見えた名前が
     *     そのまま実行の結果になる。
     *
     *     走査と目次読みはジョブに任せ、ここでは受け付けたことだけを返す。
     *     ただしパスの検証は投入のこの時点で済ませる。ジョブを作ってから
     *     失敗させると、許可の外を指したことが「失敗したジョブ」としてしか
     *     残らず、画面は投入できたと思ってしまう。
     */
    post: operations["submit_analysis_api_jobs_analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/output-roots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Choose Output Root
     * @description 利用者が出力先として選んだ場所を、この起動のあいだ覚える。
     *
     *     呼ぶのは利用者が出力先を決めた操作からだけ（画面の DirectoryPicker）。
     *     整理の投入や起動パラメータから呼ぶと、依頼が自分の許可を連れてくる形に
     *     戻り、守りが素通しになる。
     */
    post: operations["choose_output_root_api_output_roots_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/organize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Organize
     * @description アーカイブの整理をジョブとして投入する。
     *
     *     フォルダを渡されたら、ここで中身を 1 冊ずつへ展開する。フォルダを
     *     1 件のまま走らせると、進捗の総数が 1 のまま複数冊が出来上がる。
     *
     *     書き出す先は、ジョブにする前に確かめる。ジョブにして後から失敗させると、
     *     画面は投入できたと思ったまま、断る理由だけが後から届く（#58 と同じ）。
     */
    post: operations["submit_organize_api_jobs_organize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AnalyzeRequest
     * @description 出来上がる本を実行前に調べる依頼
     */
    AnalyzeRequest: {
      /**
       * Archives
       * @description 解析対象の絶対パス。フォルダを渡すと中を再帰的に辿る
       */
      archives: string[];
      /**
       * Title
       * @description 作品名
       * @default
       */
      title: string;
      /**
       * Author
       * @description 著者名
       * @default
       */
      author: string;
    };
    /**
     * AuthorCandidate
     * @description 検索で見つかった作品と、その著者
     */
    AuthorCandidate: {
      /** Title */
      title: string;
      /** Author */
      author: string;
      /** Source */
      source: string;
      /** Similarity */
      similarity: number;
    };
    /**
     * BookRef
     * @description 本 1 冊の指定。
     *
     *     名前ではなく「元のアーカイブ + その中での位置」で指す。出来上がる名前は
     *     作品名と著者で毎回変わるので、名前を鍵にすると入力欄をいじった瞬間に
     *     選択が外れる。``entry`` はアーカイブ全体が 1 冊なら空文字。
     */
    BookRef: {
      /**
       * Source
       * @description 元のアーカイブ（または画像フォルダ）の絶対パス
       */
      source: string;
      /**
       * Entry
       * @description アーカイブ内での位置
       * @default
       */
      entry: string;
      /**
       * Title
       * @description この本自身の作品名。整理済みの本だけが持つ。省くと依頼の値を使う
       */
      title?: string | null;
      /**
       * Author
       * @description この本自身の著者名。整理済みの本だけが持つ。省くと依頼の値を使う
       */
      author?: string | null;
      /** @description 巻数の訂正。省くと自動判定のまま。包みの有無が「訂正したかどうか」で、中の number が「何巻か」 */
      volume?: components["schemas"]["VolumeOverride"] | null;
    };
    /**
     * BrowseEntry
     * @description ファイル選択に出す 1 項目
     */
    BrowseEntry: {
      /** Name */
      name: string;
      /** Path */
      path: string;
      /** Is Directory */
      is_directory: boolean;
    };
    /**
     * BrowseResult
     * @description 辿っている場所と、その中身
     */
    BrowseResult: {
      /** Path */
      path: string;
      /** Parent */
      parent?: string | null;
      /** Entries */
      entries: components["schemas"]["BrowseEntry"][];
    };
    /**
     * CoverRequest
     * @description 表紙加工の依頼。分割 → 切り抜き → 回転の順に適用される
     */
    CoverRequest: {
      /**
       * Archive
       * @description 対象アーカイブの絶対パス
       */
      archive: string;
      /**
       * Name
       * @description 加工するページ名（通常は先頭）
       */
      name: string;
      /**
       * Split
       * @description 見開きの残す側（left / right）
       */
      split?: string | null;
      /**
       * Crop
       * @description 切り抜き範囲 (left, upper, right, lower)
       */
      crop?: [number, number, number, number] | null;
      /**
       * Rotate
       * @description 回転角。90 度単位
       * @default 0
       */
      rotate: number;
      /**
       * Make First
       * @description 加工した 1 枚を先頭ページ（サムネイル）へ移すかどうか
       * @default false
       */
      make_first: boolean;
      /**
       * From Original
       * @description 加工前の画像を対象にするかどうか。立てると crop は加工前の画像の画素で解釈される
       * @default false
       */
      from_original: boolean;
    };
    /**
     * CoverView
     * @description 表紙の状態。
     *
     *     寸法と見開き判定は「いま保存されている 1 枚」を指す。original は、その
     *     1 枚が加工の結果なら加工前の姿を添える。画面は加工前を対象にして枠を
     *     置き直すので、両方を 1 回の問い合わせで受け取る必要がある。
     */
    CoverView: {
      /** Name */
      name: string;
      /** Width */
      width: number;
      /** Height */
      height: number;
      /** Is Spread */
      is_spread: boolean;
      /** Target Aspect Ratio */
      target_aspect_ratio: number;
      edge_colors: components["schemas"]["EdgeColorsView"];
      /** @description 加工前の画像。一度も加工していなければ null */
      original: components["schemas"]["OriginalView"] | null;
    };
    /**
     * DroppedFile
     * @description ドロップされたファイルの手がかり
     */
    DroppedFile: {
      /** Name */
      name: string;
      /**
       * Size
       * @default 0
       */
      size: number;
    };
    /**
     * EdgeColorsView
     * @description 画像の 4 辺の縁の色（#rrggbb）。
     *
     *     切り抜き枠が画像の外へはみ出した所は、サイドカーがこの色で塗る。画面は
     *     同じ色で見本を描くので、確定する前に仕上がりが見える（#130）。向きは
     *     回す前の画像のもの。
     */
    EdgeColorsView: {
      /** Top */
      top: string;
      /** Bottom */
      bottom: string;
      /** Left */
      left: string;
      /** Right */
      right: string;
    };
    /**
     * EditsRequest
     * @description 編集済みの種類を知りたい本の一覧（#143）
     */
    EditsRequest: {
      /**
       * Paths
       * @description アーカイブの絶対パス
       */
      paths: string[];
    };
    /**
     * EditsView
     * @description 本ごとの編集済みの種類（#143）
     */
    EditsView: {
      /**
       * Edits
       * @description 受け取ったパスごとの編集の種類（thumbnail / reorder / split）。記録の無い本・読めない本は空
       */
      edits: {
        [key: string]: string[];
      };
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthView
     * @description 疎通確認
     */
    HealthView: {
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * JobAccepted
     * @description ジョブの受付結果
     */
    JobAccepted: {
      /** Id */
      id: string;
    };
    /**
     * JobDetail
     * @description ジョブ 1 件の詳細。
     *
     *     ログを返すのはここだけにする。一覧でも log を持つと、常に空配列が
     *     載ってしまい「ログが無い」と「一覧では取らない」を区別できない。
     */
    JobDetail: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** State */
      state: string;
      /** Current */
      current: number;
      /** Total */
      total: number;
      /** Message */
      message: string;
      /** Result */
      result?: unknown | null;
      /** Error */
      error?: string | null;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      /** Log */
      log: string[];
    };
    /**
     * JobList
     * @description ジョブ一覧
     */
    JobList: {
      /** Jobs */
      jobs: components["schemas"]["JobView"][];
    };
    /**
     * JobView
     * @description ジョブの状態。一覧はログを読まないので log を持たない
     */
    JobView: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** State */
      state: string;
      /** Current */
      current: number;
      /** Total */
      total: number;
      /** Message */
      message: string;
      /** Result */
      result?: unknown | null;
      /** Error */
      error?: string | null;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * LibraryConflict
     * @description 辞書へ入れられなかった作品名と、その食い違いの中身。
     *
     *     ``kept_author`` は辞書に残したままの著者。辞書にまだ無い作品名で、
     *     蔵書の側の著者が割れていた場合は null になる。``incoming_authors`` は
     *     蔵書から来た著者で、割れていれば複数入る。両方を返すのは、利用者が
     *     「辞書は A、蔵書は B」と読めるようにするため。黙って捨てると
     *     「押したのに変わらない」だけになり、どちらが正しいのか確かめられない。
     */
    LibraryConflict: {
      /** Title */
      title: string;
      /** Kept Author */
      kept_author?: string | null;
      /** Incoming Authors */
      incoming_authors: string[];
    };
    /**
     * LibraryEntries
     * @description 辞書の中身
     */
    LibraryEntries: {
      /** Entries */
      entries: components["schemas"]["LibraryEntry"][];
    };
    /**
     * LibraryEntry
     * @description タイトルと著者の対応
     */
    LibraryEntry: {
      /** Title */
      title: string;
      /** Author */
      author: string;
    };
    /**
     * LibraryImportRequest
     * @description 整理済みの蔵書から拾った対を、まとめて辞書へ入れる依頼
     */
    LibraryImportRequest: {
      /** Entries */
      entries: components["schemas"]["LibraryEntry"][];
    };
    /**
     * LibraryImportResult
     * @description 取り込みの結果。入れた対・既に在った対・断った作品名
     */
    LibraryImportResult: {
      /** Imported */
      imported: components["schemas"]["LibraryEntry"][];
      /** Unchanged */
      unchanged: components["schemas"]["LibraryEntry"][];
      /** Conflicts */
      conflicts: components["schemas"]["LibraryConflict"][];
    };
    /**
     * OperationView
     * @description 元画像に施した加工 1 つ分。params の形は kind ごとに決まる
     */
    OperationView: {
      /** Kind */
      kind: string;
      /** Params */
      params?: {
        [key: string]: unknown;
      };
    };
    /**
     * OrganizeRequest
     * @description アーカイブ整理の依頼
     */
    OrganizeRequest: {
      /**
       * Archives
       * @description 整理対象の絶対パス。フォルダを渡すと中を再帰的に辿る
       */
      archives: string[];
      /**
       * Output Directory
       * @description 出力先ディレクトリ
       */
      output_directory: string;
      /**
       * Title
       * @description 作品名
       * @default
       */
      title: string;
      /**
       * Author
       * @description 著者名
       * @default
       */
      author: string;
      /**
       * Keep Originals
       * @description 元ファイルを残すか
       * @default true
       */
      keep_originals: boolean;
      /**
       * Books
       * @description 作る本。省くと投入されたものを全部作る。与えると、その本だけを作る（空の配列は 1 冊も作らない）
       */
      books?: components["schemas"]["BookRef"][] | null;
    };
    /**
     * OriginalView
     * @description いま見ている 1 枚の、加工前の姿。
     *
     *     ZIP 内のどのエントリに入っているかは返さない。返すと、書き換えられた
     *     manifest を使って画面からアーカイブ内の任意のエントリを読ませる道ができる。
     *     画面が要るのは「どれだけ広い絵が残っているか」と「前回どこを選んだか」だけ。
     */
    OriginalView: {
      /** Width */
      width: number;
      /** Height */
      height: number;
      /** Operations */
      operations: components["schemas"]["OperationView"][];
      edge_colors: components["schemas"]["EdgeColorsView"];
    };
    /**
     * OutputRootRequest
     * @description 出力先として選んだ場所を伝える依頼
     */
    OutputRootRequest: {
      /**
       * Directory
       * @description 利用者が選んだ出力先の絶対パス
       */
      directory: string;
    };
    /**
     * OutputRootView
     * @description 覚えた出力先。
     *
     *     辿り直した形で返す。自由入力なので `.../整理後/../整理後` のような書き方も
     *     届く。画面が「どこを覚えたか」を確かめられるようにするため。
     */
    OutputRootView: {
      /**
       * Directory
       * @description 覚えた出力先（辿り直した絶対パス）
       */
      directory: string;
    };
    /**
     * PageList
     * @description アーカイブ内のページ一覧
     */
    PageList: {
      /** Archive */
      archive: string;
      /** Pages */
      pages: components["schemas"]["PageView"][];
      /** Thumbnail Widths */
      thumbnail_widths: number[];
    };
    /**
     * PageView
     * @description ページ 1 枚の情報
     */
    PageView: {
      /** Name */
      name: string;
      /** Size */
      size: number;
      /** Modified */
      modified: string;
    };
    /**
     * ReorderRequest
     * @description ページ並べ替えの依頼
     */
    ReorderRequest: {
      /**
       * Archive
       * @description 対象アーカイブの絶対パス
       */
      archive: string;
      /**
       * Order
       * @description 並べ替え後のページ名（先頭が 1 ページ目）
       */
      order: string[];
    };
    /**
     * ResolveRequest
     * @description ドロップされたものを実パスに結びつける依頼
     */
    ResolveRequest: {
      /** Files */
      files: components["schemas"]["DroppedFile"][];
    };
    /**
     * ResolveResult
     * @description 見つかったもの、見つからなかったもの、絞りきれなかったもの
     */
    ResolveResult: {
      /** Resolved */
      resolved: string[];
      /** Unresolved */
      unresolved: string[];
      /** Ambiguous */
      ambiguous: string[];
      /**
       * Searched Roots
       * @default []
       */
      searched_roots: string[];
    };
    /**
     * SplitConfirmRequest
     * @description 割った結果を書き込む依頼。行は差分ではなく全部を送る。
     *
     *     確定は連番を振り直すので、どのみち ZIP を丸ごと書き直す。全部あれば
     *     「行の名前を並べたもの＝いまのページ順」をサイドカーが照合できる。
     */
    SplitConfirmRequest: {
      /**
       * Archive
       * @description 対象アーカイブの絶対パス
       */
      archive: string;
      /**
       * Token
       * @description 走査が返した印
       */
      token: string;
      /**
       * Rows
       * @description ページ順に並べた行ぜんぶ
       */
      rows: components["schemas"]["SplitIntentRowView"][];
    };
    /**
     * SplitIntentRowView
     * @description 画面が送り返す 1 行。名前と割る位置（と結合するか）だけ。
     *
     *     寸法や出どころは受け取らない。受け取ると、画面が抱えている古い寸法で
     *     切られる余地が残る。
     */
    SplitIntentRowView: {
      /**
       * Names
       * @description この行が占める、いま存在するページ名（割った対は 2 つ）
       */
      names: string[];
      /** @description 割る位置。割らない（割る前へ戻す）なら null */
      split: components["schemas"]["SplitPositionView"] | null;
      /**
       * Merge
       * @description 隣り合う 2 ページ（names の 2 つ）を 1 枚の見開きへ結合するか。split は null にする
       * @default false
       */
      merge: boolean;
    };
    /**
     * SplitPositionView
     * @description 割る位置。行の width / height と同じ座標系で読む
     */
    SplitPositionView: {
      /** X */
      x: number;
    };
    /**
     * SplitScanRequest
     * @description 見開きを割る画面を開くための走査の依頼
     */
    SplitScanRequest: {
      /**
       * Archive
       * @description 対象アーカイブの絶対パス
       */
      archive: string;
    };
    /**
     * SuggestRequest
     * @description 外部サービスへの問い合わせ依頼
     */
    SuggestRequest: {
      /**
       * Title
       * @description 調べたい作品名。空白のみは受け付けない
       */
      title: string;
    };
    /**
     * Suggestion
     * @description 補完の結果。近い順に候補を並べ、先頭を既定として示す
     */
    Suggestion: {
      /** Title */
      title?: string | null;
      /** Author */
      author?: string | null;
      /** Candidates */
      candidates?: components["schemas"]["AuthorCandidate"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VolumeOverride
     * @description 利用者が直した巻数（#114 段階 C）。
     *
     *     巻数だけを ``int | None`` で受けず、包みにするのは ``None`` に 2 つの意味が
     *     乗るから。「まだ訂正していない」と「巻数を外す」が同じ ``null`` になり、
     *     後から見分けられない。画面（``plan.ts`` の ``selectedBooks``）は既に
     *     **全行へ** ``title`` / ``author`` の ``null`` を載せて送っているので、同じ
     *     書き方を ``volume`` にも広げると、既定の依頼が「全冊の巻数を消す」依頼に
     *     なる。包みの有無が「訂正したかどうか」で、中の ``number`` が「何巻か」。
     *
     *     ``number`` に既定値は付けない。``{"volume": {}}`` を黙って「巻数なし」と
     *     読むと、包んだ意味そのものが消える。
     *
     *     下限が 0 なのは体裁の話ではなく、往復するかどうかの話（実測）。``-1`` は
     *     ``[著者] 作品 第-01巻.zip`` になり、``organized_detector._ORGANIZED_STEM``
     *     （``第(?P<volume>\d+)巻``）に**一致しない**。つまりその本は二度と
     *     「整理済み」にならず、投入するたびに永久に作り直される。しかも同じ名前は
     *     ``VolumeDetector`` の ``第(\d+)巻`` に拾われて**第 1 巻として読み戻される**
     *     ので、利用者は「-1 巻にしたはずの本が 1 巻になっている」ものを受け取り
     *     続ける。``0`` は ``第000巻.zip`` になり 0 へ読み戻るので許す。
     */
    VolumeOverride: {
      /**
       * Number
       * @description 訂正後の巻数。null は「巻数を付けない」。省略はできない
       */
      number: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_pages_api_pages_get: {
    parameters: {
      query: {
        archive: string;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PageList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  thumbnail_api_thumb_get: {
    parameters: {
      query: {
        archive: string;
        name: string;
        width?: number;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edits_api_edits_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EditsView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolve_api_resolve_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolveResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  browse_api_browse_get: {
    parameters: {
      query?: {
        path?: string;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrowseResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_entries_api_library_entries_get: {
    parameters: {
      query?: {
        query?: string;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntries"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_entry_api_library_entries_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LibraryEntry"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_entry_api_library_entries_delete: {
    parameters: {
      query: {
        title: string;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_entries_api_library_import_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LibraryImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryImportResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggest_api_library_suggest_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SuggestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Suggestion"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  image_api_image_get: {
    parameters: {
      query: {
        archive: string;
        name: string;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  original_api_original_get: {
    parameters: {
      query: {
        archive: string;
        name: string;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cover_api_cover_get: {
    parameters: {
      query: {
        archive: string;
        name?: string | null;
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoverView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_cover_api_jobs_cover_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CoverRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_jobs_api_jobs_get: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_job_api_jobs__job_id__cancel_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_reorder_api_jobs_reorder_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_split_scan_api_jobs_split_scan_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SplitScanRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_split_api_jobs_split_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SplitConfirmRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_analysis_api_jobs_analyze_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalyzeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  choose_output_root_api_output_roots_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OutputRootRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutputRootView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_organize_api_jobs_organize_post: {
    parameters: {
      query?: {
        /** @description 使い捨てトークン */
        token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
