[supervisord]
nodaemon=true
user=node
logfile=/workspace/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/workspace/logs/supervisord.pid
directory=/workspace

[include]
files = /vnc-config/conf.d/*.conf

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock